// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EnableDebug","status":true,"description":"","parameters":{}},
{"name":"DarkPlasma_ImportExportSaveFile","status":true,"description":"セーブデータのインポート・エクスポート機能","parameters":{"textAreaRect":"{\"x\":\"208\",\"y\":\"500\",\"width\":\"400\",\"height\":\"400\"}","okButtonPos":"{\"x\":\"308\", \"y\":\"520\"}","cancelButtonPos":"{\"x\":\"508\", \"y\":\"520\"}","menuButtonType":"1","importButtonPos":"{\"x\":\"680\", \"y\":\"16\"}","exportButtonPos":"{\"x\":\"750\", \"y\":\"16\"}","exportHelpText":"表示されているテキストを保存してください。","importHelpText":"セーブデータのテキストを貼り付けてください。","buttonImages":"{\"ok\":\"buttonOk\",\"cancel\":\"buttonCancel\",\"import\":\"buttonImport\",\"export\":\"buttonExport\"}"}}
];
